### ISSUE TITLE
Error stops.txt not found

### ISSUE THREAD

**Issue by brechtvdv** [iRail/brail2gtfs-rt#13]
```
Aug 10, 2015 4:42:39 PM com.opentransport.rdfmapper.nmbs.StationDatabase getAllStationIdsFromGTFSFeed
SEVERE: null
java.io.FileNotFoundException: stops.txt (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at java.io.FileInputStream.<init>(FileInputStream.java:101)
    at java.io.FileReader.<init>(FileReader.java:58)
    at com.opentransport.rdfmapper.nmbs.StationDatabase.readTxtGetAllStations(StationDatabase.java:89)
    at com.opentransport.rdfmapper.nmbs.StationDatabase.getAllStationIdsFromGTFSFeed(StationDatabase.java:77)
    at com.opentransport.rdfmapper.nmbs.SortedMapper.map(SortedMapper.java:66)
    at com.opentransport.rdfmapper.nmbs.SortedMapper.<init>(SortedMapper.java:41)
    at com.opentransport.rdfmapper.nmbs.Main.scrapeLiveBoards(Main.java:142)
    at com.opentransport.rdfmapper.nmbs.Main$1.run(Main.java:44)
```

**Comment by brechtvdv** [comment]
I got this error when first running, can you check this @TimTijssens ?

**Comment by TimTijssens** [comment]
@brechtvdv  did u use the the gtfs feed ? like mentioned in the read me 

From the readme ? 
You should have an unzipped gtfs feed of the Belgium railway unzipped in the root directory. This can be downloaded from http://gtfs.irail.be/nmbs/nmbs-latest.zip

**Comment by brechtvdv** [comment]
:+1:
